language: python
sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - pip install tox coveralls

script:
  - tox -v -e py

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
    coveralls
