language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - pip install tox coveralls

script:
  - tox -v -e py

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
    coveralls
